name: 'wiz-cli'
on: [pull_request]

jobs:
  wiz-cli-iac-scan:
    name: 'Wiz-cli IaC Scan'
    runs-on: ubuntu-latest
    environment: wiz-keys
    env:
      SCAN_PATH: "." # Set the relative path in the repo to scan
      POLICY: "Default IaC policy" # Set the desired Wiz-cli policy to use
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
      WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Check out repository
    #  uses: actions/checkout@v2
      run: |
        export REPO_PATH="${GITHUB_WORKSPACE}/repo"
        if [ -d "${REPO_PATH}" ]; then rm -Rf ${REPO_PATH}; fi
        git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/AcqSec/wiz_acqsec_terragoat.git ${REPO_PATH}
        if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
          export GITHUB_SHA=$(cat $GITHUB_EVENT_PATH | jq -r .pull_request.head.sha)
        fi
        cd ${REPO_PATH}
        git checkout ${GITHUB_SHA}

    - name: Download Wiz-cli
      run: curl -o wizcli https://wizcli.app.wiz.io/wizcli && chmod +x wizcli

    - name: Authenticate to Wiz
      run: ./wizcli auth --id "$WIZ_CLIENT_ID" --secret "$WIZ_CLIENT_SECRET"

    - name: Run wiz-cli IaC scan
      run: ./wizcli iac scan --path $SCAN_PATH --policy "$POLICY"
